language: python
python:
  - "3.5"
cache: pip3

env:
- DB=mongodb MONGODB_URI="mongodb://localhost:27017/testing"

install:
  - pip install -r requirements.txt
services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15
  - mongo testing --eval 'db.users.insert({"addDatestampToPosts":"true","tokens":[{"name":"my-token","token":"64504d74a4dc4bad26d863c0a4ab29e5","_id":{"$oid":"595fe42edf127b560b68963a"}}]})'


script:
  - python -m unittest